// DO NOT EDIT THIS FILE. COPY AND PASTE THIS FORMAT INTO A NEW FILE TITLED 'awsConfig.js' FILE

module.exports = {
  accessKeyId: 'ACCESS KEY ID',
  secretAccessKey: 'SECRET ACCESS KEY',
  region: 'AWS S3 REGION',
};